config/routes.rb
Rails.application.routes.draw do
   devise_scope :player do
    root "public/sessions#new"
  end

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_scope :player do
    post 'players/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

   namespace :admin do
      resources :posts do
      resources :comments, only:[:index, :show, :destroy]
      end
      resources :players, only:[:index, :show, :edit, :update]
      get 'homes/top'
  end

   namespace :public do
     get 'tag_search' => 'tag_search#tag_search'
  end
  namespace :public do
    get "search" => "searches#search"
    get 'top' => "homes#top"
    get 'about'=>"homes#about",as: "about"

    get 'players/confirm' , to:'players#confirm'
    patch 'players/leave' , to:'players#leave'
    resources :players, only:[:show, :index, :edit, :update] do

    member do
      get :favorites
    end

    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

   post 'posts/confirm' , to:'posts#confirm'
   get 'posts/completion' , to:'posts#completion'
   get 'posts/posting' , to:'posts#posting'
   resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
   end

   resources :groups, only:[:new, :create, :edit, :update, :show, :index, :destroy] do
   resources :group_approvals, only:[:new, :create, :destroy,:update] do
    delete "reject", on: :member
   end
   resource :group_players, only: [:create, :destroy]
   end
   get "groups/:id/approvals" => "groups#approvals", as: :approvals


  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :player
   belongs_to :post
   validates :thought,presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @comments = Comment.where(post_id: params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end

   private
  def comment_params
    params.require(:comment).permit(:thought)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">コメント一覧</h1>
    <table class="table mt-3">
      <thead class="table-light">
        <tr>
          <th class="col-2">名前</th>
          <th class="col-8">コメント</th>
          <th class="col-1"></th>
          <th class="col-1"></th>
        </tr>
      </thead>
      <% @comments.each do |comment| %>
        <tr class="table-light">
          <td class="col-2"><%= comment.player.last_name + comment.player.first_name %></td>
          <td class="col-8"><%= comment.thought %></td>
          <td class="col-1"><%= comment.created_at.strftime('%Y/%m/%d/%H:%M') %></td>
          <td class="col-1">
            <%= link_to '削除', admin_post_comment_path(comment.post, comment), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-sm btn-danger" %>
          </td>
        </tr>
      <% end %>
    </table>
</div>