config/routes.rb
Rails.application.routes.draw do
   devise_scope :player do
    root "public/sessions#new"
  end

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_scope :player do
    post 'players/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

   namespace :admin do
      resources :posts do
      resources :comments, only:[:index, :show, :destroy]
      end
      resources :players, only:[:index, :show, :edit, :update]
      get 'homes/top'
  end

   namespace :public do
     get 'tag_search' => 'tag_search#tag_search'
  end
  namespace :public do
    get "search" => "searches#search"
    get 'top' => "homes#top"
    get 'about'=>"homes#about",as: "about"

    get 'players/confirm' , to:'players#confirm'
    patch 'players/leave' , to:'players#leave'
    resources :players, only:[:show, :index, :edit, :update] do

    member do
      get :favorites
    end

    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

   post 'posts/confirm' , to:'posts#confirm'
   get 'posts/completion' , to:'posts#completion'
   get 'posts/posting' , to:'posts#posting'
   resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
   end

   resources :groups, only:[:new, :create, :edit, :update, :show, :index, :destroy] do
   resources :group_approvals, only:[:new, :create, :destroy,:update] do
    delete "reject", on: :member
   end
   resource :group_players, only: [:create, :destroy]
   end
   get "groups/:id/approvals" => "groups#approvals", as: :approvals


  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum play_style: { enjoy: 0, kill_move: 1, rank_priority: 2, hide: 3 }
         enum search: { player: 0, post: 1}
         enum search_select: { perfect_match: 0, forward_match: 1, backward_match: 2, partial_match: 3}

        has_many :favorites, dependent: :destroy
        has_many :favorite_posts, through: :favorites, source: :post
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :group_players, dependent: :destroy
         has_many :groups, through: :group_players
         has_many :group_approvals, dependent: :destroy
         has_many :calendars, dependent: :destroy
         has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         has_many :followings, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower
         has_one_attached :profile_image, dependent: :destroy

         validates :last_name,presence: true
         validates :first_name,presence: true
         validates :nickname,presence: true
         validates :platform,presence: true
         validates :addicted_game,presence: true
         validates :play_style,presence: true
         validates :is_active, inclusion: {in: [true, false]}

         def self.playerlooks(search, word)
           if search == "perfect_match"
             @player = Player.where("nickname LIKE? OR platform LIKE? OR addicted_game LIKE? OR play_style LIKE?","#{word}", "#{word}","#{word}%","#{word}%")
           elsif search == "forward_match"
             @player = Player.where("nickname LIKE? OR platform LIKE? OR addicted_game LIKE? OR play_style LIKE?","#{word}%", "#{word}","#{word}%","#{word}%")
           elsif search == "backward_match"
             @player = Player.where("nickname LIKE? OR platform LIKE? OR addicted_game LIKE? OR play_style LIKE?","%#{word}", "#{word}","#{word}%","#{word}%")
           elsif search == "partial_match"
             @player = Player.where("nickname LIKE? OR platform LIKE? OR addicted_game LIKE? OR play_style LIKE?","%#{word}%", "#{word}","#{word}%","#{word}%")
           else
             @player = Player.all
           end
         end


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
          # 指定したユーザーをフォローする
  def follow(player)
    active_relationships.create(followed_id: player.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(player)
    active_relationships.find_by(followed_id: player.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(player)
    followings.include?(player)
  end

  def self.guest
    find_or_create_by!(email: 'g@g') do |player|
      player.last_name = 'ゲスト'
      player.first_name = 'ログイン'
      player.nickname = 'ゲスログ'
      player.platform = 'ps4'
      player.addicted_game = 'ゲーム'
      player.password = 'gggggg'
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @players = Player.all
  end 
  
  def show
    @player = Player.find(params[:id])
  end 
  
  def edit
    @player = Player.find(params[:id])
  end 
  
  def update
    @player = Player.find(params[:id])
    #render plain: player_params
    #return
    if @player.update!(player_params)
      redirect_to admin_players_path
    else
      render "edit"
    end
  end
  
   private
   def player_params
     params.require(:player).permit(:last_name, :first_name, :nickname, :email, :platform, :addicted_game, :play_style, :is_active)
   end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/views/admin/players/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-12 mx-auto'>
     <h1 class="form-group text-center">プレイヤー編集</h1>
            <%= form_with model: @player, url: admin_player_path(@player), method: :patch do |f| %>
        <table class="table table mt-5">
         <tr class="table-light">
           <th>プレイヤーネーム</th>
           <td><% if @player.profile_image.attached? %>
                <%= image_tag @player.profile_image,size:"50x50" %>
               <% else %>
                <%= image_tag 'no_image', size: "50x50" %>
               <% end %>
               <%= @player.last_name + @player.first_name %>
           </td>
         </tr>
         
         <tr class="table-light">
           <th>ニックネーム</th>
           <td><%= @player.nickname %></td>
         </tr>
           
         <tr class="table-light">
           <th>プラットフォーム</th>
           <td><%= @player.platform %></td>
         </tr>
           
          <tr class="table-light">
           <th>はまっているゲーム</th>
           <td><%= @player.addicted_game %></td>
         </tr>
         <tr class="table-light">
           <th>プレイスタイル</th>
           <td><%= @player.play_style_i18n %></td>
         </tr>
         <tr class="table-light">
           <th>販売ステータス</th>
           <td>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, "利用中", value: true %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "退会済み", value: false %>
           </td>
          </tr>
        </table>
        <div class="row d-flex justify-content-center">
          <%= f.submit '変更を保存', class: "mt-5 btn btn-success form-control" %>
        </div>
         <% end %>
     </div>
   </div>
 </div>

app/views/admin/players/index.html.erb
<h1 class="form-group text-center">プレイヤー一覧</h1>
  <div class="container">
    <div class="row">
      <div class='col-md-12 mx-auto'>
        <table class="table table mt-5">
          <thead class="table-light">
            <tr>
              <th>プレイヤーネーム</th>
              <th>ニックネーム</th>
              <th>会員ステータス</th>
              <th></th>
            </tr>
          </thead>
          <% @players.each do |players| %>
          <tr class="table-light">
            <td><% if players.profile_image.attached? %>
                  <%= image_tag players.profile_image,size:"50x50" %>
                <% else %>
                  <%= image_tag 'no_image', size: "50x50" %>
                <% end %>
                <%= players.last_name + players.first_name %>
            </td>
            <td><%= players.nickname %></td>
            <td><% if players.is_active %>
              <div style="color: red;">利用中</div>
                 <% else %>
               <div style="color: blue;">退会済み</div>
                 <% end %>
               </td>
               <td><%= link_to "詳細へ", admin_player_path(players) %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/admin/players/show.html.erb
<div class="container">
  <div class="row">
     <div class='col-md-12 mx-auto'>
      <h1 class="form-group text-center">プレイヤー詳細</h1>
        <table class="table table mt-5">
          <tr class="table-light">
            <th>プレイヤーネーム</th>
            <td><% if @player.profile_image.attached? %>
                  <%= image_tag @player.profile_image,size:"100x100" %>
                <% else %>
                  <%= image_tag 'no_image', size: "100x100" %>
                <% end %>
                <%= @player.last_name + @player.first_name %>
            </td>
          </tr>

          <tr class="table-light">
            <th>ニックネーム</th>
            <td><%= @player.nickname %></td>
          </tr>

          <tr class="table-light">
            <th>プラットフォーム</th>
            <td><%= @player.platform %></td>
          </tr>

          <tr class="table-light">
            <th>はまっているゲーム</th>
            <td><%= @player.addicted_game %></td>
          </tr>

          <tr class="table-light">
            <th>プレイスタイル</th>
            <td><%= @player.play_style_i18n %></td>
          </tr>

          <tr class="table-light">
            <th>会員ステータス</th>
            <td><% if @player.is_active %>
              <div style="color: red;">利用中</div>
            <% else %>
              <div style="color: blue;">退会済み</div>
            <% end %>
            </td>
          </tr>
       </table>
      <div class="form-group text-center mt-5">
        <div class="actions">
          <%= link_to "プロフィールを編集する", edit_admin_player_path(@player),class: "form-control btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>