config/routes.rb
Rails.application.routes.draw do
   devise_scope :player do
    root "public/sessions#new"
  end

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_scope :player do
    post 'players/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

   namespace :admin do
      resources :posts do
      resources :comments, only:[:index, :show, :destroy]
      end
      resources :players, only:[:index, :show, :edit, :update]
      get 'homes/top'
  end

   namespace :public do
     get 'tag_search' => 'tag_search#tag_search'
  end
  namespace :public do
    get "search" => "searches#search"
    get 'top' => "homes#top"
    get 'about'=>"homes#about",as: "about"

    get 'players/confirm' , to:'players#confirm'
    patch 'players/leave' , to:'players#leave'
    resources :players, only:[:show, :index, :edit, :update] do

    member do
      get :favorites
    end

    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

   post 'posts/confirm' , to:'posts#confirm'
   get 'posts/completion' , to:'posts#completion'
   get 'posts/posting' , to:'posts#posting'
   resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
   end

   resources :groups, only:[:new, :create, :edit, :update, :show, :index, :destroy] do
   resources :group_approvals, only:[:new, :create, :destroy,:update] do
    delete "reject", on: :member
   end
   resource :group_players, only: [:create, :destroy]
   end
   get "groups/:id/approvals" => "groups#approvals", as: :approvals


  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/button/_blue_button.html.erb
<% if blue_btn == "my3" %>
  <%= f.submit text, class: "btn btn-primary form-control my-3" %>
<% elsif blue_btn == "my1" %> 
  <%= f.submit text, class: "btn btn-primary form-control my-1" %>
<% elsif blue_btn == "post-confirm" %>
  <%= f.submit "確定", class:'form-control btn btn-primary  mt-5 mb-5' %>
<% else %>
  <%= f.submit text, class: "btn btn-primary mt-4 form-control" %>
<% end %>

app/views/layouts/button/_blue_lt_button.html.erb
<% if blue_lt_btn %>
  <%= link_to "いいね一覧", favorites_public_player_path(player.id), class: "btn btn-primary  form-control my-3" %>
<% else %>
  <%= link_to "退会しない", public_top_path, :class => "btn btn-primary ms-3" %>
<% end %>

app/views/layouts/button/_green_button.html.erb
<% if green_btn == "post-edit" %>
  <%= link_to "投稿を編集する", edit_public_post_path(post), class:'btn bg-success form-control text-white mb-2' %>
  <% elsif green_btn == "player-edit" %>
    <%= link_to "プロフィールを編集する", edit_public_player_path(player), class: "btn btn-success form-control mt-5" %>
  <% elsif green_btn == "group-apply" %>
    <%= link_to '加入申請', new_public_group_group_approval_path(group), class: "btn btn-sm btn-success" %>
  <% elsif green_btn == "group-approval" %>
    <%= link_to '承認', public_group_group_players_path(group, approval_id: approval.first.id, status:"approval"), method: :post, class: "btn btn-sm btn-success" %>
  <% else %>
    <%= link_to 'グループ詳細', public_group_path(group), class: "group_#{group.id} btn btn-sm btn-success" %>
  <% end %>

app/views/layouts/button/_light_blue_button.html.erb
<%= f.submit text, class:'btn btn-info form-control mt-5 mb-5' %>

app/views/layouts/button/_red_button.html.erb
<% if red_btn == "post-delete" %>
  <%= link_to "投稿を削除する", public_post_path(post), method: :delete, data: { confirm: "本当に削除しますか？"} ,class:'btn bg-danger form-control text-white' %>
<% elsif red_btn == "player-confirm" %>
  <%= link_to "退会する", public_players_confirm_path, class: "btn btn-danger btn-sm text-white form-control p-2" %>
<%  elsif red_btn == "group-approval-cancel" %>
  <%= link_to '申請取消', public_group_group_approval_path(group), method: :delete, class: "btn btn-sm btn-danger" %>
<%  elsif red_btn == "group-approval-reject" %>
   <%= link_to '却下', reject_public_group_group_approval_path(group, approval_id: approval.first.id,status:"rejected"), method: :delete, class: "btn btn-sm btn-danger" %>
<%  elsif red_btn == "group-exit" %>
  <%= link_to 'グループ退出', public_group_group_players_path(group), method: :delete, class: "btn btn-sm btn-danger", data: { confirm: "本当にグループを退出しますか？" } %>
<% else %>
  <%= link_to "退会する", public_players_leave_path(player.id), method: :patch, :class => "btn btn-danger ms-3", data: { confirm: "本当に退会しますか？" }  %>
<% end %>