config/routes.rb
Rails.application.routes.draw do
   devise_scope :player do
    root "public/sessions#new"
  end

  devise_for :players,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  devise_scope :player do
    post 'players/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

   namespace :admin do
      resources :posts do
      resources :comments, only:[:index, :show, :destroy]
      end
      resources :players, only:[:index, :show, :edit, :update]
      get 'homes/top'
  end

   namespace :public do
     get 'tag_search' => 'tag_search#tag_search'
  end
  namespace :public do
    get "search" => "searches#search"
    get 'top' => "homes#top"
    get 'about'=>"homes#about",as: "about"

    get 'players/confirm' , to:'players#confirm'
    patch 'players/leave' , to:'players#leave'
    resources :players, only:[:show, :index, :edit, :update] do

    member do
      get :favorites
    end

    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

   post 'posts/confirm' , to:'posts#confirm'
   get 'posts/completion' , to:'posts#completion'
   get 'posts/posting' , to:'posts#posting'
   resources :posts, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only:[:create, :destroy]
    resource :favorites, only:[:create, :destroy]
   end

   resources :groups, only:[:new, :create, :edit, :update, :show, :index, :destroy] do
   resources :group_approvals, only:[:new, :create, :destroy,:update] do
    delete "reject", on: :member
   end
   resource :group_players, only: [:create, :destroy]
   end
   get "groups/:id/approvals" => "groups#approvals", as: :approvals


  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul class="alert alert-warning">
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container mt-5 border-top">
    <div class="row">
      <p class="mx-auto font-weight-bolder" style="font-family: 'OCRB'">CopyRight Taiki Takemoto</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!--playerログイン時-->
  <ul style="display: flex">
    <% if player_signed_in? %>
      <li>
        <%= link_to public_top_path, class: 'nav-link font-weight-bolder' do %>
          <i class="fa-solid fa-house"></i> ホーム
        <% end %>
      </li>
      <li>
        <%= link_to public_player_path(current_player), class: 'nav-link font-weight-bolder' do %>
          <i class="fa-solid fa-user"></i> マイページ
        <% end %>
      </li>
      <li>
        <%= link_to new_public_post_path, class: 'nav-link font-weight-bolder' do %>
          <i class="fa-solid fa-users"></i> 募集開始
        <% end %>
      </li>
      <li>
        <%=  link_to public_posts_path, class: 'nav-link font-weight-bolder' do %>
          <i class="fa-solid fa-clock-rotate-left"></i> 投稿履歴
        <% end %>
      </li>
      <li>
        <%=  link_to destroy_player_session_path, method: :delete, class: 'nav-link font-weight-bolder' do %>
          <i class="fas fa-sign-out-alt"></i> ログアウト
        <% end %>
      </li>
      <!--adminログイン時-->
    <% elsif admin_signed_in? %>
      <li>
        <%= link_to admin_homes_top_path, class: 'nav-link font-weight-bolder' do %>
          <i class="fa-solid fa-house"></i> ホーム
        <% end %>
      </li>
      <li>
        <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link font-weight-bolder' do %>
          <i class="fas fa-sign-out-alt"></i> ログアウト
        <% end %>
      </li>
      <!--ログアウト時-->
    <% else %>
      <li>
        <%= link_to new_player_registration_path, class: 'nav-link font-weight-bolder' do %>
          <i class="fa-solid fa-user-plus"></i> 新規登録
        <% end %>
      </li>
      <li>
        <%= link_to new_player_session_path, class: 'nav-link font-weight-bolder' do %>
          <i class="fas fa-sign-in-alt"></i> ログイン
        <% end %>
      </li>
      <li>
        <%= link_to players_guest_sign_in_path, method: :post, class: 'nav-link font-weight-bolder' do %>
          <i class="fas fa-sign-in-alt"></i> ゲストログイン
        <% end %>
      </li>
    <% end %>
  </ul>
</header>

app/views/layouts/_posts.html.erb
<% if hover %>
  <table class='table table-hover'>
<% else %>
  <table class='table'>
<% end %>
  <%= render "layouts/thead" %>
    <% @posts.each do |post| %>
      <tr onclick='window.location="<%= public_post_path(post) %>"' role="link", class="table-light">
        <td><%= post.player.nickname %></td>
        <td><%= post.game_name %></td>
        <td><%= post.game_genre %></td>
        <td><%= post.participate_number %>人</td>
        <td><%= post.start_time.strftime('%m/%d/%H:%M') %></td>
        <td><%= post.ending_time.strftime('%m/%d/%H:%M') %></td>
        <td><%= post.today_tension_i18n %></td>
        <td><%= link_to post.content,public_post_path(post) %></td>
      </tr>
    <% end %>
</table>

app/views/layouts/_thead.html.erb
<thead>
  <tr class="table-light">
    <th class="col-1">募集者名</th>
    <th class="col-1">ゲーム名</th>
    <th class="col-1">ジャンル</th>
    <th class="col-1">募集人数</th>
    <th class="col-1">始める時間</th>
    <th class="col-1">終わる時間</th>
    <th class="col-2">今日のテンション</th>
    <th class="col-4">ひとこと</th>
  </tr>
</thead>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameCommunity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5c4a1fefd6.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <div class="notice">
      <% if flash[:notice] %>
       <%= flash[:notice] %>
      <% end %>
    </div>

    <div class="alert2">
      <% if flash[:alert] %>
       <%= flash[:alert] %>
      <% end %>
    </div>

    <%= render "layouts/header"%>


    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>